-- CRIAÇÃO DO BANCO DE DADOS

CREATE DATABASE DB_TESTE_LOCAL

--PARA UTILIZAR O BANCO DE DADOS CRIADO

USE DB_TESTE_LOCAL 

-- CRIAÇÃO DA TABELA TESTE

CREATE	TABLE	TABLE_TESTE
(
CODIGO		INTEGER	NOT NULL	,
DESCRICAO	VARCHAR(255)		,
DATA_REGISTRO	DATETIME
)

ALTER	TABLE	TABLE_TESTE	
ADD	CONSTRAINT	PK_TABLE_TESTE_CODIGO
PRIMARY	KEY(CODIGO)

