-- EXECUÇÃO DA SCRIPT

DECLARE
@V_DATA_ATUAL	DATETIME	=	GETDATE()

EXECUTE	TABLE_TESTE_SP_MNT
	'EXC'				,--@INP_STATUS		
	0				,--@INP_CODIGO		
	'TEXTO TESTE'			,--@INP_DESCRICAO		
	@V_DATA_ATUAL			,--@INP_DATA_REGISTRO	
	''				,--@OUT_CODIGO	
	''				,--@OUT_DESCRICAO		
	''				,--@OUT_DATA_REGISTRO	
	''				,--@OUT_COD_ERRO		
	''				--@OUT_DESC_ERRO	
	
	
	--SELECT * FROM	TABLE_TESTE 